name: meal_planner
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3
  firebase_auth: ^6.1.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  riverpod: ^2.6.1
  infinite_calendar_view: ^2.10.1
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  google_mlkit_text_recognition: ^0.15.0
  image_picker: ^1.0.7
  permission_handler: ^12.0.1
  url_launcher: ^6.3.0
  flutter_native_splash: ^2.4.7
  flutter_svg: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  fake_cloud_firestore: ^4.0.0
  build_runner: ^2.4.8
  freezed: ^2.5.8
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.4
  test: ^1.26.2

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/splash_logo.png
    - assets/merged20.svg

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash_logo.png
  android: true
  ios: true
  web: false
  android_12:
    icon_background_color: "#FFFFFF"
